[book]
authors = ["Luca Palmieri"]
language = "ko"
src = "src"
title = "100개의 연습 문제로 Rust 배우기"

[preprocessor.exercise-linker]
exercise_root_url = "https://github.com/mainmatter/100-exercises-to-learn-rust/tree/main/exercises"

[preprocessor.link-shortener]
base_url = "https://ruex.io"
mapping = "link2alias.json"
verify = false
after = ["exercise-linker"]

[output.html]
git-repository-url = "https://github.com/mainmatter/100-exercises-to-learn-rust"
preferred-dark-theme = "navy"
smart-punctuation = true
default-theme = "light"
additional-css = ["src/css/custom.css"]

[output.html.playground]
runnable = false

[output.html.search]
limit-results = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

