name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install exercise plugin
        run: cargo install --path helpers/mdbook-exercise-linker
      - name: Install link shortener plugin
        run: cargo install --path helpers/mdbook-link-shortener
      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - name: Build book
        env:
          LINK_SHORTENER_VERIFY: "true"
        run: |
          cd book
          mdbook build
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          args: |
            --exclude-loopback
            --require-https
            --no-progress
            book/book/html/
      # Upload the HTML book as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: book
          path: book/book/html

  is_fresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y jq
      - run: |
          ./helpers/json2redirects.sh book/link2alias.json > site/_redirects
      # Verify nothing has changed, meaning that the redirect file is up-to-date
      - run: |
          git diff --exit-code site/_redirects

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
